from bright.apigen import cygen as cg

from nose.tools import assert_equal

toaster_desc = {
    'name': 'Toaster',
    'header_filename': 'toaster.h',
    'namespace': 'bright',
    'library_docstring': "I am the Toaster lib! Hear me sizzle!", 
    'parents': ['FCComp'],
    'attrs': {
        'nslices': 'uint',
        'toastiness': 'str',
        'rate': 'float',
        },
    }


exp_cpppxd = \
"""################################################
#                 Warning!                     #
# This file has been auto-generated by Bright. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################

cdef extern from "toaster.h" namespace "bright":

    cdef cppclass Toaster(FCComp):
        # attributes
        uint nslices
        float rate
        str toastiness

        # methods

"""

def test_gencpppxd():
    obs = cg.gencpppxd(toaster_desc)
    assert_equal(obs, exp_cpppxd)
