################################################
#                 WARNING!                     #
# This file has been auto-generated by Bright. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################
from libcpp.map cimport map as cpp_map
from libcpp.string cimport string as std_string
from libcpp.vector cimport vector as cpp_vector

cdef extern from "reactor_parameters.h" namespace "bright":

    cdef cppclass ReactorParameters:
        # constructors
        ReactorParameters() except +

        # attributes
        double BUt
        int batches
        double branch_ratio_cutoff
        int burn_regions
        cpp_vector[double] burn_times
        std_string burnup_via_constant
        double clad_radius
        double cladding_density
        cpp_map[std_string, double] cladding_form
        double coolant_density
        cpp_map[std_string, double] coolant_form
        double flux
        double fuel_density
        cpp_map[std_string, double] fuel_form
        double fuel_radius
        std_string lattice_type
        double open_slots
        double pnl
        bint rescale_hydrogen
        double specific_power
        double total_slots
        double unit_cell_pitch
        bint use_disadvantage_factor
        double void_radius

        # methods



