################################################
#                 WARNING!                     #
# This file has been auto-generated by Bright. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################
from bright cimport cpp_fccomp
from bright cimport cpp_fluence_point
from bright cimport cpp_reactor_parameters
from libcpp.map cimport map as cpp_map
from libcpp.set cimport set as cpp_set
from libcpp.string cimport string as std_string
from libcpp.vector cimport vector as cpp_vector
from pyne cimport cpp_material

cdef extern from "reactor1g.h" namespace "bright":

    cdef cppclass Reactor1G(cpp_fccomp.FCComp):
        # constructors
        Reactor1G() except +
        Reactor1G(std_string) except +
        Reactor1G(cpp_set[std_string]) except +
        Reactor1G(cpp_set[std_string], std_string) except +
        Reactor1G(cpp_reactor_parameters.ReactorParameters) except +
        Reactor1G(cpp_reactor_parameters.ReactorParameters, std_string) except +
        Reactor1G(cpp_reactor_parameters.ReactorParameters, cpp_set[std_string]) except +
        Reactor1G(cpp_reactor_parameters.ReactorParameters, cpp_set[std_string], std_string) except +

        # attributes
        double A_IHM
        int B
        cpp_vector[double] BU_F_
        double BUd
        cpp_map[int, cpp_vector[double]] BUi_F_
        cpp_vector[double] D_F_
        cpp_vector[double] F
        double Fd
        double MWC
        double MWF
        cpp_map[int, cpp_vector[double]] Mj_F_
        cpp_map[int, double] NiC
        cpp_map[int, double] NiF
        cpp_vector[double] P_F_
        double P_NL
        double S_O
        double S_T
        cpp_vector[double] SigmaCa_F_
        cpp_vector[double] SigmaCtr_F_
        cpp_vector[double] SigmaFa_F_
        cpp_vector[double] SigmaFtr_F_
        double VC
        double VF
        cpp_map[std_string, double] coolant_chemical_form
        cpp_vector[double] dC_F_
        cpp_vector[double] dF_F_
        double deltaR
        cpp_map[int, cpp_vector[double]] di_F_
        int fd
        cpp_map[std_string, double] fuel_chemical_form
        double k
        cpp_vector[double] k_F_
        cpp_vector[double] kappaC_F_
        cpp_vector[double] kappaF_F_
        double l
        cpp_vector[double] lattice_E_F_
        cpp_vector[double] lattice_F_F_
        std_string lattice_flag
        std_string libfile
        cpp_material.Material mat_feed_act
        cpp_material.Material mat_feed_lan
        cpp_material.Material mat_feed_tru
        cpp_material.Material mat_feed_u
        cpp_material.Material mat_prod_act
        cpp_material.Material mat_prod_lan
        cpp_material.Material mat_prod_tru
        cpp_material.Material mat_prod_u
        cpp_map[int, double] miC
        cpp_map[int, double] miF
        cpp_map[int, double] niC
        cpp_map[int, double] niF
        double phi
        cpp_map[int, cpp_vector[double]] pi_F_
        double r
        bint rescale_hydrogen_xs
        double rhoC
        double rhoF
        double target_BU
        double tru_cr
        bint use_zeta
        cpp_vector[double] zeta_F_

        # methods
        void BUd_bisection_method() except +
        double batch_average(double) except +
        double batch_average(double, std_string) except +
        double batch_average_k(double) except +
        cpp_material.Material calc() except +
        cpp_material.Material calc(cpp_map[int, double]) except +
        cpp_material.Material calc(cpp_material.Material) except +
        void calc_Mj_F_() except +
        void calc_Mj_Fd_() except +
        double calc_deltaR() except +
        double calc_deltaR(cpp_map[int, double]) except +
        double calc_deltaR(cpp_material.Material) except +
        void calc_mat_prod() except +
        void calc_sub_mats() except +
        double calc_tru_cr() except +
        void calc_zeta() except +
        void calc_zeta_cylindrical() except +
        void calc_zeta_planar() except +
        void calc_zeta_spherical() except +
        void calibrate_P_NL_to_BUd() except +
        cpp_fluence_point.FluencePoint fluence_at_BU(double) except +
        void fold_mass_weights() except +
        void initialize(cpp_reactor_parameters.ReactorParameters) except +
        void lattice_E_cylindrical(double, double) except +
        void lattice_E_planar(double, double) except +
        void lattice_E_spherical(double, double) except +
        void lattice_F_cylindrical(double, double) except +
        void lattice_F_planar(double, double) except +
        void lattice_F_spherical(double, double) except +
        void loadlib() except +
        void loadlib(std_string) except +
        void run_P_NL(double) except +


