################################################
#                 WARNING!                     #
# This file has been auto-generated by Bright. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################
"""no docstring for enrichmentparameters, please file a bug report!
"""
from libc.stdlib cimport free



cdef class EnrichmentParameters:
    """no docstring for EnrichmentParameters, please file a bug report!"""

    # constuctors
    def __cinit__(self, *args, **kwargs):
        self._inst = NULL
        self._free_inst = True

        # cached property defaults


    def __init__(self):
        """"""
        self._inst = new cpp_enrichment_parameters.EnrichmentParameters()
    
    
    def __dealloc__(self):
        if self._free_inst:
            free(self._inst)

    # attributes
    property M0:
        """no docstring for M0, please file a bug report!"""
        def __get__(self):
            return float((<cpp_enrichment_parameters.EnrichmentParameters *> self._inst).M0)
    
        def __set__(self, value):
            (<cpp_enrichment_parameters.EnrichmentParameters *> self._inst).M0 = <double> value
    
    
    property Mstar_0:
        """no docstring for Mstar_0, please file a bug report!"""
        def __get__(self):
            return float((<cpp_enrichment_parameters.EnrichmentParameters *> self._inst).Mstar_0)
    
        def __set__(self, value):
            (<cpp_enrichment_parameters.EnrichmentParameters *> self._inst).Mstar_0 = <double> value
    
    
    property N0:
        """no docstring for N0, please file a bug report!"""
        def __get__(self):
            return float((<cpp_enrichment_parameters.EnrichmentParameters *> self._inst).N0)
    
        def __set__(self, value):
            (<cpp_enrichment_parameters.EnrichmentParameters *> self._inst).N0 = <double> value
    
    
    property alpha_0:
        """no docstring for alpha_0, please file a bug report!"""
        def __get__(self):
            return float((<cpp_enrichment_parameters.EnrichmentParameters *> self._inst).alpha_0)
    
        def __set__(self, value):
            (<cpp_enrichment_parameters.EnrichmentParameters *> self._inst).alpha_0 = <double> value
    
    
    property j:
        """no docstring for j, please file a bug report!"""
        def __get__(self):
            return int((<cpp_enrichment_parameters.EnrichmentParameters *> self._inst).j)
    
        def __set__(self, value):
            (<cpp_enrichment_parameters.EnrichmentParameters *> self._inst).j = value
    
    
    property k:
        """no docstring for k, please file a bug report!"""
        def __get__(self):
            return int((<cpp_enrichment_parameters.EnrichmentParameters *> self._inst).k)
    
        def __set__(self, value):
            (<cpp_enrichment_parameters.EnrichmentParameters *> self._inst).k = value
    
    
    property xP_j:
        """no docstring for xP_j, please file a bug report!"""
        def __get__(self):
            return float((<cpp_enrichment_parameters.EnrichmentParameters *> self._inst).xP_j)
    
        def __set__(self, value):
            (<cpp_enrichment_parameters.EnrichmentParameters *> self._inst).xP_j = <double> value
    
    
    property xW_j:
        """no docstring for xW_j, please file a bug report!"""
        def __get__(self):
            return float((<cpp_enrichment_parameters.EnrichmentParameters *> self._inst).xW_j)
    
        def __set__(self, value):
            (<cpp_enrichment_parameters.EnrichmentParameters *> self._inst).xW_j = <double> value
    
    
    # methods

