################################################
#                 WARNING!                     #
# This file has been auto-generated by xdress. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################


cimport reactor1g
from bright cimport cpp_fast_reactor1g

cdef class FastReactor1G(reactor1g.Reactor1G):
    pass




