################################################
#                 WARNING!                     #
# This file has been auto-generated by Bright. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################


cimport reactor1g
from bright cimport cpp_light_water_reactor1g

cdef class LightWaterReactor1G(reactor1g.Reactor1G):
    pass




