################################################
#                 WARNING!                     #
# This file has been auto-generated by Bright. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################
cimport cpp_reprocess
cimport fccomp

cdef class Reprocess(fccomp.FCComp):
    pass
