################################################
#                 WARNING!                     #
# This file has been auto-generated by Bright. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################
cimport fccomp
from bright cimport cpp_storage

cdef class Storage(fccomp.FCComp):
    pass


